Work around ARM Docker build segfaults [ci skip]
It's temporary hiccups, so there's a retry loop in there now. This also
switches to Alpine 3.20, uses make instead of ninja (or samurai) and
calls make directly instead of going through cmake to not get parallel
compilation, which overall reduces the frequency of the faults.

diff --git a/pkg/docker/Dockerfile b/pkg/docker/Dockerfile
--- a/pkg/docker/Dockerfile
+++ b/pkg/docker/Dockerfile
@@ -1,18 +1,29 @@
-FROM alpine:3.19 as common
+FROM alpine:3.20 as common
 RUN apk add --no-cache libbz2 libmicrohttpd libsodium qt5-qtbase qt5-qtbase-sqlite qt5-qtwebsockets
 
 ## Build container
 FROM common as builder
-RUN apk add cargo cmake g++ libmicrohttpd-dev libsodium-dev qt5-qtbase-dev qt5-qtwebsockets-dev samurai
+RUN apk add cargo cmake g++ libmicrohttpd-dev libsodium-dev make qt5-qtbase-dev qt5-qtwebsockets-dev
 
+# On ARM, the C and C++ compilers have hiccups that make them randomy segfault.
+# We just retry the compilation up to ten times to work around that.
 ARG version=main
 RUN mkdir -p /build \
     && cd /build \
     && wget -O /build/drawpile.zip https://github.com/drawpile/Drawpile/archive/${version}.zip \
     && unzip drawpile.zip \
     && cd Drawpile-*/ \
-    && cmake --preset linux-release-qt5-server-ninja -DENABLE_ARCH_NATIVE=OFF -DINSTALL_DOC=OFF -DSOURCE_ASSETS=OFF \
-    && cmake --build build \
+    && cmake --preset linux-release-qt5-server-make -DENABLE_ARCH_NATIVE=OFF -DINSTALL_DOC=OFF -DSOURCE_ASSETS=OFF \
+    && while ! make -C build; do \
+        tries=$((tries + 1)); \
+        if [ "$tries" -gt 9 ]; then \
+            echo "Compilation attempt $tries failed, giving up"; \
+            exit 1; \
+        else \
+            echo "Compilation attempt $tries failed, trying again"; \
+        fi; \
+        echo 'Compilation failed, trying again'; \
+    done  \
     && mv build/bin/drawpile-srv /build
 
 # Final deployment image
