Add retry for Intel macOS packaging
Because the runner is really flaky and sometimes fails at the first
attempt, so we just try three times now.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -237,7 +237,21 @@ jobs:
             collect_symbols: false
             signpath: false
             sccache_triplet: x86_64-apple-darwin
-            packager: cpack --verbose --config build/CPackConfig.cmake -C Release
+            # The runner is really flaky at this step, retry it a few times.
+            packager: |
+              attempts=0
+              limit=3
+              while : ; do
+                cpack --verbose --config build/CPackConfig.cmake -C Release && break
+                attempts=$((attempts+1))
+                if [ "$attempts" -lt "$limit" ]; then
+                  echo "Packing attempt $attempts/$limit failed, retrying..."
+                  sleep 3
+                else
+                  echo "Packing attempt $attempts/$limit failed, bailing out."
+                  exit 1
+                fi
+              done
 
           - os: macos-14
             cross_os: ''
